services:
  menu:
    build: .
    container_name: menu-app
    restart: always
    ports:
      - "5000:5000"          # cambia 5000 a sinistra se vuoi un'altra porta
    volumes:
      - menu_data:/data      # il men√π sopravvive ai riavvii
    environment:
      ADMIN_PASSWORD: "fiumara"   # password per lo staff
      SECRET_KEY: "stringa-casuale-lunga-e-segreta"

volumes:
  menu_data:
